spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KANGTEMPLATE?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

